### ISSUE TITLE
How can I set up a dedicated IP for each user?

### ISSUE THREAD

**Issue by abolfazl-biria** [yousseb/softether-server#3]
I want to give a dedicated IP to the user. What should I do for this purpose?

**Comment by abolfazl-biria** [comment]
Let me ask you a different question
How can I set a setting so that the user's IP never changes?

**Comment by abolfazl-biria** [comment]
Let me ask you better questions, please
I want each user to have a unique IP and no one can connect to it
What settings do I need to make for this?

**Comment by yousseb** [comment]
This is beyond the scope of this setup. In such case, you will probably need to setup a dedicated DHCP server and reserve the IP per MAC address. 

More info probably in this thread:
https://www.vpnusers.com/viewtopic.php?t=2607
